
> **Reference:** VanderPlas, Jake. **Python data science handbook**: Essential tools for working with data. " O'Reilly Media, Inc.", 2016.

# CHAPTER 3 - PART 1


As we saw, NumPy's ndarray data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks. While it serves this purpose very well, its limitations become clear when we need more flexibility (**attaching labels to data, working with missing data, etc.**) and when attempting operations that do not map well to element-wise broadcasting (groupings, pivots, etc.), each of which is an important piece of analyzing the less structured data available in many forms in the world around us. Pandas, and in particular its **Series** and **DataFrame** objects, **builds on the NumPy array structure** and provides efficient access to these sorts of "data munging" tasks that occupy much of a data scientist's time.

In this chapter, we will focus on the mechanics of using **Series**, **DataFrame**, and related structures effectively. We will use examples drawn from real datasets where appropriate, but these examples are not necessarily the focus.

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'2.2.2'

# 1- Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as **enhanced versions of NumPy structured arrays** in which the **rows and columns are identified with labels** rather than simple integer indices.

Before we go any further, let's introduce these three fundamental Pandas data structures: the **Series**, **DataFrame**, and **Index**.


1.   The Pandas **Series** Object
2.   The Pandas **DataFrame** Object
3.   The Pandas **Index** Object


We will start our code sessions with the standard NumPy and Pandas imports:

## (1) The Pandas `Series` Object

A Pandas **Series** is a **one-dimensional array of indexed data**. It can be created from a list or array as follows:

### Series as one-dimensional array

A **one-dimensional array of indexed data**: `values` and `index`.

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

As we see in the preceding output, the **Series** wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes.

**The values** are simply a familiar **NumPy array:**

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
type(data.values)

numpy.ndarray

**The index** is an **array-like object** of type pd.Index, which we'll discuss in more detail momentarily:

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
type(data.index)

pandas.core.indexes.range.RangeIndex

Like with a NumPy array, data can be **accessed by the associated index** via the familiar Python square-bracket notation:

In [7]:
data[1]

np.float64(0.5)

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

np.float64(0.5)

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [12]:
data[5]

np.float64(0.5)

### Series as dictionary

In this way, you can think of a Pandas **Series** a bit like a specialization of a Python dictionary. A **dictionary** is a structure that **maps arbitrary keys to a set of arbitrary values**, and a **Series** is a structure that **maps typed keys to a set of typed values**. This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas **Series** makes it **much more efficient than Python dictionaries for certain operations**.

We can make the **Series**-as-dictionary analogy even more clear by constructing a **Series** object directly from a Python dictionary:

**Keys** are **Index** and **Values** are **Values (Data)**.

In [13]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

By default, a **Series** will be created where the index is drawn from the sorted keys. From here, typical **dictionary-style** item **access** can be performed:

In [14]:
population['California']

np.int64(38332521)

Unlike a dictionary, though, the **Series** also supports **array-style operations** such as **slicing**:

In [15]:
population['Texas': 'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

### Constructing Series objects

`pd.Series(data, index=index)`

where index is an optional argument, and data can be one of many entities.

For example, data can be a **list or NumPy array**, in which case index defaults to an integer sequence:

In [16]:
# Data can be a list
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

Data can be a **scalar**, which is repeated to fill the specified index:

In [17]:
# A scalar
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

Data can be a **dictionary**, in which index defaults to the sorted dictionary keys:

In [18]:
# A dictionary
# Series: {index: value}
pd.Series({2:'a', 1:'b', 3:'c'})
# what if: data[2:1]?
# int sequential index or the given index?

2    a
1    b
3    c
dtype: object

In each case, the **index can be explicitly set** if a different result is preferred:

In [19]:
# A keys-subset of a dictionary
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

Notice that in this case, the **Series** is populated only with the explicitly identified keys.

## (2) The Pandas DataFrame Object

### DataFrame as two-dimensional array

2D array is a sequence of 1D columns.

**DataFrame** is a sequence of **Series** objects.

**Series** are the columns.

To demonstrate this, let's first construct a new **Series** listing the area of each of the five states discussed in the previous section:

In [20]:
area_dict = {'California': 423967,
             'Texas': 695662,
             'New York': 141297,
             'Florida': 170312,
             'Illinois': 149995}

In [21]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [22]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Now that we have this along with the population **Series** from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [23]:
# Having two Series objects:
# area and population, with the same index.
# DataFrame: {column_name: series}
states = pd.DataFrame({'population': population,  # Create DataFrame from dictionary
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

**Important Attributes:** index, columns

Like the **Series** object, the **DataFrame** has an `index` attribute that gives access to the **index labels**:

In [24]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the **DataFrame** has a `columns` attribute, which is an **Index** object holding the **column labels**:

In [25]:
states.columns

Index(['population', 'area'], dtype='object')

Thus the **DataFrame** can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

### DataFrame as dictionary (dictionary of columns)

Similarly, we can also think of a **DataFrame** as a specialization of a dictionary. Where a dictionary maps a key to a value, a **DataFrame** maps a column name to a **Series** of column data.

**Dict** maps a **key** to a **value**.

**DataFrame** maps a **column name** to a **Series of column data**.

For example, asking for the 'area' attribute returns the **Series** object containing the areas we saw earlier:

In [26]:
# In DataFrame, indexing here means columns
# unlike Series, indexing means rows

# For a DataFrame, data['col0']
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Notice the potential point of confusion here: in a two-dimensional `NumPy` array, **data[0]** will return **the first row**. For a `DataFrame`, **data['col0']** will return **the first column**. Because of this, it is probably better to think about DataFrames as generalized dictionaries rather than generalized arrays, though both ways of looking at the situation can be useful.

### Constructing DataFrame objects


**From a single Series object.** A **DataFrame** is a collection of **Series** objects, and a single-column **DataFrame** can be constructed from a single **Series**:

In [27]:
# 1- From a single Series object (single column)
pd.DataFrame(population, columns=['population'])
# single Series = single column

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

**From a list of dicts.** Any list of dictionaries can be made into a **DataFrame**. We'll use a simple list comprehension to create some data:

In [28]:
# 2- From a list of dicts (list of rows)
data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(data)
# each dict = row, {column_name: row_value}
# dict keys = column names
# dict values = values of one row
pd.DataFrame(data)

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

   a  b
0  0  0
1  1  2
2  2  4

Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e., "not a number") values:

In [29]:
# If some keys in the dictionary are missing,
# Pandas will fill them in with NaN (i.e.,  “not a number”) values
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])  # Create DataFrame from dictionary
# DataFrame: [row0_dict, row1_dict]

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

**From a dictionary of Series objects.** As we saw before, a **DataFrame** can be constructed from a dictionary of **Series** objects as well:

In [30]:
# 3- From a dictionary of Series objects
# DataFrame: {column_name: column_series}
pd.DataFrame({'population': population,  # Create DataFrame from dictionary
              'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

**From a two-dimensional NumPy array.** Given a two-dimensional array of data, we can create a **DataFrame** with any specified column and index names. If omitted, an integer index will be used for each:

In [31]:
# 4- From a two-dimensional Numpy array
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])
# If 'columns' and 'index' omitted,
# an integer  index will be used for each.

        foo       bar
a  0.824253  0.429766
b  0.640449  0.776040
c  0.796088  0.806338

In [32]:
# Missing 'columns' argument
pd.DataFrame(np.random.rand(3, 2),
             index=['a', 'b', 'c'])

          0         1
a  0.352383  0.506875
b  0.087778  0.752343
c  0.997379  0.755865

In [33]:
# Missing 'index' argument
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'])

        foo       bar
0  0.240436  0.098070
1  0.477202  0.308385
2  0.706823  0.519080

In [34]:
# Missing 'index' and 'columns' arguments
pd.DataFrame(np.random.rand(3, 2))

          0         1
0  0.452673  0.581580
1  0.702221  0.430931
2  0.997181  0.643458

## (3) The Pandas `Index` Object

Can be thought of as:


*   an immutable array
*   or as an  ordered set (technically a multiset, as **Index** objects may contain repeated values).

### Index as immutable array

The **Index** object in many ways operates like an array. For example, we can use standard Python indexing notation to retrieve values or slices:

In [35]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [36]:
ind[1]

np.int64(3)

In [37]:
ind[::2]

Index([2, 5, 11], dtype='int64')

**Index** objects also have many of the **attributes familiar from NumPy arrays**:

In [38]:
# Has many of the attributes familiar from NumPy arrays
print(ind)
print(ind.size, ind.shape, ind.ndim, ind.dtype)

Index([2, 3, 5, 7, 11], dtype='int64')
5 (5,) 1 int64

One difference between **Index** objects and NumPy arrays is that **indices are immutable**—that is, they cannot be modified via the normal means:

In [39]:
# One difference between Index objects and NumPy arrays
# is that indices are immutable.

# Uncomment the following:
# ind[1] = 0  # Error

This immutability makes it safer to share indices between multiple DataFrames and arrays, without the potential for side effects from inadvertent index modification.

### Index as ordered set

 Set Operations:


*   Intersection
*   Union

*   Difference
*   Symmetric Difference

In [40]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
print(indA)
print(indB)

Index([1, 3, 5, 7, 9], dtype='int64')
Index([2, 3, 5, 7, 11], dtype='int64')

In [41]:
# Intersection
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [42]:
# Union
indA.union(indB)  # no duplicates

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [43]:
# Difference
indA.difference(indB)  # In A and not in B

Index([1, 9], dtype='int64')

In [44]:
# Symmetric Difference
indA.symmetric_difference(indB)  # = Union - Intersection

Index([1, 2, 9, 11], dtype='int64')

# 2- Data Indexing and Selection

In Chapter 2, we looked in detail at methods and tools to access, set, and modify values in NumPy arrays. These included indexing (e.g., arr[2, 1]), slicing (e.g., arr[:, 1:5]), masking (e.g., arr[arr > 0]), fancy indexing (e.g., arr[0, [1, 5]]), and combinations thereof (e.g., arr[:, [1, 5]]). Here we'll look at similar means of accessing and modifying values in Pandas **Series** and **DataFrame** objects. If you have used the NumPy patterns, the corresponding patterns in Pandas will feel very familiar, though there are a few quirks to be aware of.

We'll start with the simple case of the one-dimensional **Series** object, and then move on to the more complicated two-dimensional **DataFrame** object.

## (1) Data Selection in `Series`

### Series as dictionary

Like a dictionary, the **Series** object provides a mapping from a collection of keys to a collection of values:

In [45]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [46]:
data['b']

np.float64(0.5)

We can also use dictionary-like Python expressions and methods to examine the  keys/indices and values

In [47]:
'a' in data

True

In [48]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [49]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [50]:
data.items()

**Series** objects can even be modified with a dictionary-like syntax. Just as you can extend a dictionary by assigning to a new key, you can extend a **Series** by assigning to a new index value:

In [51]:
#  Extending Series by assigning to a new key (new index)
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as one-dimensional array


A **Series** builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays—that is, slices, masking, and fancy indexing. Examples of these are as follows:


1.   Slicing by Explicit **Index**
2.   Slicing by Implicit Integer **Index**
3.   Masking
4.   Fancy Indexing

In [52]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [53]:
# 1- Slicing by 'explicit' index (the specified ind)
data['a': 'c']  # 'c' is included

a    0.25
b    0.50
c    0.75
dtype: float64

In [54]:
# 2- Slicing by 'implicit' integer index (the sequential ind)
data[0:2]  # data[2] is NOT included

a    0.25
b    0.50
dtype: float64

In [55]:
# 3- Masking
data[data > 0.3]

b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [56]:
data[(data > 0.3) & (data < 0.8)]  # () is needed

b    0.50
c    0.75
dtype: float64

In [57]:
# 4- Fancy Indexing
data[['a', 'e', 'b']]  # [[]] is needed

a    0.25
e    1.25
b    0.50
dtype: float64

### Indexers: loc, iloc

Among these, slicing may be the source of the most confusion.

**Examples:**

*   **Final Index Inclusion**: Slicing with an explicit index (i.e., data['a':'c']), the final index is included in  the slice, while when you’re slicing with an implicit index (i.e., data[0:2]), the final  index is excluded from the slice.
*   **Explicit Integer Index:**
If  your **Series** has an explicit integer index, an indexing operation such as data[1] will  use the explicit indices, while a slicing operation like data[1:3] will use the implicit  Python-style index.

In [58]:
# Explicit Integer Index
data = pd.Series(['a', 'b', 'c'],
                 index=[1, 3, 5])  # index is integer
data

1    a
3    b
5    c
dtype: object

In [59]:
# Explicit Index when Indexing
data[1]

'a'

In [60]:
# Implicit Index when Slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides  some special `indexer` **attributes** (not methods) that explicitly expose certain indexing schemes.
1.  loc
2. iloc

**1- loc:** Always Explicit **Index**

The loc attribute allows indexing and slicing that always references the explicit  index.

In [61]:
data

1    a
3    b
5    c
dtype: object

In [62]:
# Indexing
data.loc[1]  # Explicit

'a'

In [63]:
# Slicing
data.loc[1:3]  # Explicit

1    a
3    b
dtype: object

**2- iloc:** Always Implicit **Index**

The iloc attribute allows indexing and slicing that always references the implicit  Python-style index

In [64]:
data

1    a
3    b
5    c
dtype: object

In [65]:
# Indexing
data.iloc[1]  # Implicit

'b'

In [66]:
# Slicing
data.iloc[1:3]  # Implicit

3    b
5    c
dtype: object

One guiding principle of Python code is that “explicit is better than implicit.” The  explicit nature of loc and iloc make them very useful in maintaining clean and readable code; especially in the case of integer indexes, I recommend using these both to  make code easier to read and understand, and to prevent subtle bugs due to the  mixed indexing/slicing convention.

**The Old 'ix' Attribute:**
- AttributeError: ... no attribute 'ix'	.ix was deleted in pandas 1.0.
- Use .loc for labels or .iloc for positions.

## (2) Data Selection in `DataFrame`

Recall that a **DataFrame** acts in many ways like a two-dimensional or structured array,  and in other ways like a dictionary of **Series** structures sharing the same index.

### DataFrame as dictionary

The first analogy we will consider is the **DataFrame** as a dictionary of related **Series** objects. Let's return to our example of areas and populations of states:

In [67]:
# DataFrame: dict {column_name: column_series}
area = pd.Series({'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135})
data = pd.DataFrame({'area': area, 'pop': pop})  # Create DataFrame from dictionary
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

The individual **Series** that make up the columns of the **DataFrame** can be accessed via dictionary-style indexing of the column name:

In [68]:
# 1- Dict-Style Column Access:
# The individual column Series can be accessed via:
# dict-style indexing of column name
data['area']  # data[column_name] ---> its column_series

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Equivalently, we can use attribute-style access with column names that are strings:

In [69]:
# 2- Attribute-Style Column Access:
# Equivalently, we can use attribute-style access with column names that are strings:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

This attribute-style column access actually accesses the exact same object as the dictionary-style access:

In [70]:
# Both access the exact same object
data.area is data['area']

True

Though this is a useful shorthand, keep in mind that it does not work for all cases!  For example, **if the column names are not strings**, or **if the column names conflict  with methods of the DataFrame**, this attribute-style access is not possible. For example, the **DataFrame** has a pop() method, so data.pop will point to this rather than the  "pop" column.

In [71]:
# Here not equivalent
data.pop is data['pop']

False

Like with the **Series** objects discussed earlier, this dictionary-style syntax can also be used to modify the object, in this case to add a new column:

In [72]:
# 3- Adding New Column (dict-style):
# by assigning new column name
data['density'] = data['pop'] / data['area']  # Element-wise
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

This shows a preview of the straightforward syntax of element-by-element arithmetic between **Series** objects.

### DataFrame as two-dimensional array

As mentioned previously, we can also view the **DataFrame** as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute:

In [73]:
# 1- Access the raw underlying data (.values)
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [74]:
print(type(data.values))  # a normal numpy.ndarray

<class 'numpy.ndarray'>

With this picture in mind, we can do many familiar array-like observations on the  **DataFrame** itself.

In [75]:
#  2- Transpose
data.T

           California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

**Indexing:**

When it comes to indexing of **DataFrame** objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array. In particular, passing a single index to an array accesses a row:

In [76]:
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [77]:
data.values[0]  # Single row values

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

and passing a single "index" to a **DataFrame** accesses a column:

In [78]:
data['area']  # Single column series

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Indexers: loc, iloc

Using the iloc indexer, we can  index the underlying array as if it is a simple NumPy array (using the implicit  Python-style index), but the **DataFrame** index and column labels are maintained in  the result

In [79]:
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [80]:
data.iloc[:3, :2]  # First 3 rows and first 2 cols

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [81]:
data.loc[:'New York', :'pop']

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

Any of the familiar NumPy-style data access patterns can be used within these indexers.

In [82]:
# For example, in the loc indexer we can combine masking and fancy indexing:
data.loc[data.density > 100, ['pop', 'density']]

               pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

Any of these indexing conventions may also be used to set or modify values

In [83]:
data

              area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [84]:
# Change a cell
data.iloc[0, 2] = 90
data

              area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

To build up your fluency in Pandas data manipulation, I suggest spending some time with a simple **DataFrame** and exploring the types of indexing, slicing, masking, and fancy indexing that are allowed by these various indexing approaches.



### Additional indexing conventions

There are a couple extra indexing conventions that might seem at odds with the preceding discussion, but nevertheless can be very useful in practice. First, while indexing refers to columns, slicing refers to rows:

In [85]:
data['Florida':'Illinois']

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

Such slices can also refer to rows by number rather than by index:

In [86]:
data[1:3]

            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

Similarly, direct masking operations are also interpreted row-wise rather than column-wise:

In [87]:
data[data.density > 100]

            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

These two conventions are syntactically similar to those on a NumPy array, and while these may not precisely fit the mold of the Pandas conventions, they are nevertheless quite useful in practice.

# 3- UFuncs: Operating on Data in Pandas

Ufuncs: Universal Functions

Pandas includes a couple useful twists, however: for **unary operations** like negation  and trigonometric functions, these ufuncs will *preserve index and column* labels in the  output, and for **binary operations** such as addition and multiplication, Pandas will  *automatically align indices* when passing the objects to the ufunc. This means that  keeping the context of data and **combining data from different sources**—both potentially error-prone tasks with raw NumPy arrays—become essentially foolproof ones  with Pandas.

## (1) UFuncs: Index Preservation

Any NumPy ufunc will work on  Pandas **Series** and **DataFrame** objects.

In [88]:
# Create Series object
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [89]:
# Create DataFrame object
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

If we apply a NumPy ufunc on either of these objects, the result will be another Pandas object **with the indices preserved**.

In [90]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

Or, for a slightly more complex calculation:

In [91]:
np.sin(df * np.pi / 4)

          A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

## (2) UFuncs: Index Alignment

For binary operations on two **Series** or **DataFrame** objects, Pandas will align indices  in the process of performing the operation. This is very convenient when you are  working with incomplete data, as we’ll see in some of the examples that follow.

### Index alignment in `Series`

As an example, suppose we are combining two different data sources, and find only the top three US states by area and the top three US states by population:

In [92]:
# The top three US states by area.
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967},
                 name='area')  # name of the series
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [93]:
# The top three US states by population.
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127},
                       name='population')
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

Let's see what happens when we divide these to compute the population density:

In [94]:
# Let’s see what happens when we divide these to compute the population density:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

The resulting array contains the **union** of indices of the two input arrays, which we  could determine using standard Python set arithmetic on these indices:

In [95]:
set(area.index) | set(population.index)

{'Alaska', 'California', 'New York', 'Texas'}

In [96]:
# Or,
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

This index matching is implemented this way for any of Python’s built-in arithmetic expressions; any missing values are filled in with NaN by default:

In [97]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using NaN values is not the desired behavior, we can modify the fill value using  appropriate object methods in place of the operators. For example, calling A.add(B)  is equivalent to calling A + B, but allows optional explicit specification of the fill value  for any elements in A or B that might be missing:

In [98]:
A.add(B, fill_value=0)  # the results is in new Series object

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index alignment in `DataFrame`

A similar type of alignment takes place for both columns and indices when you are  performing operations on DataFrames:

In [99]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
# list('AB') is ['A', 'B']
A

   A   B
0  1  11
1  5   1

In [100]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B
# NOTE: the order of the columns is different and one new column

   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [101]:
A + B
# NOTE: add the corresponding cells (same index, same column)
# so, automatically handles the column order difference

      A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

Notice that indices are aligned correctly irrespective of their order in the two objects,  and indices in the result are sorted.

As was the case with **Series**, we can use the associated object’s arithmetic method and pass any desired `fill_value` to be used in place  of missing entries.

In [102]:
A

   A   B
0  1  11
1  5   1

In [103]:
A.stack()
# .stack(): DataFrame --> Series
# Input: A wide DataFrame with columns A and B.
# Action: It "pushes" the column names down to become a new level of the row index.
# Output: A Series with a multi-level (hierarchical) index.

# .stack() "pivots" the column labels into the innermost index level.
# Think of it as taking the horizontal header and rotating it into a vertical sub-index.

0  A     1
   B    11
1  A     5
   B     1
dtype: int64

In [104]:
A.stack().mean()

np.float64(4.5)

In [105]:
A

   A   B
0  1  11
1  5   1

In [106]:
B

   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [107]:
# Here we’ll fill with the mean of all values in A
# (which we compute  by first stacking the rows of A):
fill = A.stack().mean()
A.add(B, fill_value=fill)

      A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

### Mapping between Python operators and Pandas methods

The following table lists Python operators and their equivalent Pandas object methods:

| Python operator | Pandas method(s) |
|-----------------|------------------|
| + | add() |
| - | sub(), subtract() |
| * | mul(), multiply() |
| / | truediv(), div(), divide() |
| // | floordiv() |
| % | mod() |
| ** | pow() |

In pandas, most rows in the following table list a "shorthand" method and a "long-form" alias (e.g., mul() and multiply()).

Historically, these were added to make the API more readable or to match NumPy's naming conventions.

For almost all practical purposes, there is no functional difference between the alternatives in a given row. They execute the exact same underlying code.

**Why use these methods instead of operators (like + or -)?**

You might wonder why you'd ever use data.add(other) instead of just data + other. The methods provide a critical parameter that the standard Python operators do not: The `axis` and `fill_value` parameters.

## (3) UFuncs: Operations Between `DataFrame` and `Series`

When you are performing operations between a **DataFrame** and a **Series**, the index  and column alignment is similarly maintained.

Operations between a **DataFrame** and  a **Series** are similar to operations between a two-dimensional and one-dimensional  NumPy array.

Consider one common operation, where we find the difference of a  two-dimensional array and one of its rows:

In [108]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [109]:
print(A.shape)
print(A[0].shape)

(3, 4)
(4,)

In [110]:
A - A[0]
# According to NumPy’s broadcasting rules,
# subtraction between a two-dimensional array and one of its rows is  applied row-wise.

# Broadcasting Steps:
# Shapes: (3, 4) - (4,)
# Step 1: (3, 4) - (*1, 4)
# Step 2: (3, 4) - (*3, 4) --> then element-wise sub

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In Pandas, the convention similarly operates **row-wise** by default:

In [111]:
# Now, using pandas not numpy
df = pd.DataFrame(A, columns=list('QRST'))
df

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [112]:
print(type(df.iloc[0]))
df.iloc[0]  # the first row Series

<class 'pandas.core.series.Series'>

Q    3
R    8
S    2
T    4
Name: 0, dtype: int64

In [113]:
df - df.iloc[0]  # df.iloc[0] is the first row
# Same result as before but using pandas

   Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

If you would instead like to operate **column-wise**, you can use the object methods  mentioned earlier, while specifying the axis keyword:

In [114]:
df

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [115]:
print(type(df['R']))
df['R']  # the R's col Series

<class 'pandas.core.series.Series'>

0    8
1    6
2    1
Name: R, dtype: int64

In [116]:
df.subtract(df['R'], axis=0)  # df - column df['R'] but column-wise sub

   Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [117]:
df.sub(df['R'], axis=0)  # Using the shorthand sub(), same function

   Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

Note that these **DataFrame**/**Series** operations, like the operations discussed before,  will automatically align indices between the two elements:

In [118]:
df

   Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [119]:
halfrow = df.iloc[0, ::2]  # Row 0, every other column (take one leave one, step=2)
print(type(halfrow))
halfrow

<class 'pandas.core.series.Series'>

Q    3
S    2
Name: 0, dtype: int64

In [120]:
df - halfrow  # Automaticaaly align indices between the DataFrame and the Series
# So, it performed: the Q and S columns minus the Q and S value of halfrow
# and since no R and T columns in halfrow, NaN results are got

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

This preservation and alignment of indices and columns means that operations on  data in Pandas will always maintain the data context, which prevents the types of silly  errors that might come up when you are working with heterogeneous and/or misaligned data in raw NumPy arrays.